### ISSUE TITLE
how do u use it?

### ISSUE THREAD

**Issue by GAGARR** [korylprince/ls-relay-cert#1]

**Comment by korylprince** [comment]
There are two parts to this repository.

* The [gen-ls-cert](https://github.com/korylprince/ls-relay-cert/tree/master/cmd/gen-ls-cert) tool, which is an alternative to Lightspeed's makeca tool
* The ls-relay-cert server, which works with MicroMDM to generate unique trusted CA certs on the fly for clients instead of using a single CA cert for all of your clients

Based on a quick look at your profile, you're likely looking for a way to bypass Lightspeed Relay, and that's not what this tool is for.
